<#
.SYNOPSIS
    Context Guardian — Stop hook that monitors transcript size and auto-generates handoff files.

.DESCRIPTION
    Runs on the Claude Code "Stop" event. Reads the session transcript from stdin,
    checks its size, and if above threshold generates a compact handoff file so
    the user can seamlessly start a fresh session.

    Does NOT block or interrupt work. Only writes a handoff file and prints a warning.

.NOTES
    Hook type: Stop (command)
    Timeout: 5s
    Non-blocking, fail-open
#>

param(
    [int]$ThresholdKB = 2048  # ~300K tokens ≈ 2MB transcript JSON
)

$ErrorActionPreference = 'SilentlyContinue'

try {
    # Read hook input from stdin (JSON with session_id, transcript_path, cwd, etc.)
    $inputJson = $null
    if (-not [Console]::IsInputRedirected) { exit 0 }

    $raw = [Console]::In.ReadToEnd()
    if (-not $raw) { exit 0 }

    $input = $raw | ConvertFrom-Json
    if (-not $input) { exit 0 }

    $transcriptPath = $input.transcript_path
    $sessionId = $input.session_id
    $cwd = $input.cwd

    if (-not $transcriptPath -or -not (Test-Path $transcriptPath)) { exit 0 }

    # Check transcript size
    $fileInfo = Get-Item $transcriptPath
    $sizeKB = [math]::Round($fileInfo.Length / 1024)

    if ($sizeKB -lt $ThresholdKB) { exit 0 }

    # Determine project memory directory by scanning project dirs
    $memoryDir = $null
    $projectsBase = Join-Path $env:USERPROFILE ".claude\projects"

    if (Test-Path $projectsBase) {
        $cwdNorm = $cwd.Replace('\', '/').TrimEnd('/').ToLower()
        $projectDirs = Get-ChildItem -Path $projectsBase -Directory

        foreach ($dir in $projectDirs) {
            $slugParts = $dir.Name.ToLower() -split '-' | Where-Object { $_.Length -ge 2 }
            $matchScore = 0
            foreach ($part in $slugParts) {
                if ($cwdNorm.Contains($part)) { $matchScore++ }
            }
            if ($slugParts.Count -gt 0 -and $matchScore -ge ($slugParts.Count / 2)) {
                $candidate = Join-Path $dir.FullName "memory"
                if (Test-Path $candidate) {
                    $memoryDir = $candidate
                    break
                }
            }
        }
    }

    if (-not $memoryDir) {
        # Fallback: create a directory from cwd slug
        $projectSlug = $cwd -replace '[:\\\/]', '-' -replace '^-+', '' -replace '-+$', ''
        $memoryDir = Join-Path $env:USERPROFILE ".claude\projects\$projectSlug\memory"
        New-Item -Path $memoryDir -ItemType Directory -Force | Out-Null
    }

    # Read last ~50KB of transcript for context extraction
    $transcriptContent = ''
    try {
        $bytes = [System.IO.File]::ReadAllBytes($transcriptPath)
        $startPos = [math]::Max(0, $bytes.Length - 51200)
        $chunk = [System.Text.Encoding]::UTF8.GetString($bytes, $startPos, $bytes.Length - $startPos)
        $transcriptContent = $chunk
    } catch {
        $transcriptContent = ''
    }

    # Generate handoff file
    $date = Get-Date -Format 'yyyy_MM_dd_HHmm'
    $handoffPath = Join-Path $memoryDir "session_handoff_auto.md"

    $handoff = @"
---
name: Auto-generated session handoff
description: Context Guardian auto-handoff when transcript reached ${sizeKB}KB (~$([math]::Round($sizeKB * 150))K tokens)
type: project
generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
session_id: $sessionId
transcript_size_kb: $sizeKB
working_directory: $cwd
---

# Session Handoff (Auto-Generated)

**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
**Session:** $sessionId
**Transcript size:** ${sizeKB}KB (~$([math]::Round($sizeKB * 150))K tokens)
**Working directory:** $cwd

## How to Use
Start a new Claude Code session and paste:
``Read the auto-generated handoff at $handoffPath then continue where the previous session left off.``

## Session State
This handoff was auto-generated by the Context Guardian hook because the session
transcript exceeded the ${ThresholdKB}KB threshold. For best results, start a fresh
session to avoid the cumulative context cost (~$sizeKB KB re-read every turn).

## Recent Activity
The session was working in: $cwd
Check the project's memory files and plans directory for detailed state.

## Key Locations
- Plans: ~/.claude/plans/
- Memory: $memoryDir
- Scripts: ~/.claude/scripts/
- Hooks: ~/.claude/hooks/
"@

    $handoff | Out-File -FilePath $handoffPath -Encoding utf8 -Force

    # Output warning (visible to user in Claude Code)
    $pct = [math]::Min(100, [math]::Round(($sizeKB / 4096) * 100))

    # Return JSON result for the Stop hook
    $result = @{
        result = "warn"
        message = "[Context Guardian] Transcript at ${sizeKB}KB (~${pct}% of comfortable limit). Handoff saved to $handoffPath. Consider starting a fresh session for lower token costs."
    } | ConvertTo-Json -Compress

    Write-Output $result

} catch {
    # Fail-open: never block the session
    exit 0
}
